#!/data/data/com.termux/files/usr/bin/sh
set -e

export PATH=$PATH:/system/xbin:/system/bin

mount -t tmpfs -o mode=755,nodev,noexec,nosuid tmpfs /sys/fs/cgroup
for cg in blkio cpu cpuacct cpuset devices freezer memory; do
        if [ ! -d "/sys/fs/cgroup/${cg}" ]; then
                mkdir -p "/sys/fs/cgroup/${cg}"
        fi

        if ! mountpoint -q "/sys/fs/cgroup/${cg}"; then
                mount -t cgroup -o "${cg}" cgroup "/sys/fs/cgroup/${cg}" || true
        fi
done

mkdir -p /sys/fs/cgroup/systemd;
mount -t cgroup cgroup -o none,name=systemd /sys/fs/cgroup/systemd;
